# Generated by Django 4.2.2 on 2023-08-30 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[(1, 'Days'), (2, 'Nights'), (3, 'Mids')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leads.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modex', models.IntegerField(max_length=3)),
                ('discrepancy', models.CharField(max_length=50)),
                ('text_body', models.TextField()),
                ('passdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.passdown')),
            ],
        ),
    ]
