# Generated by Django 4.2.2 on 2023-08-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_passdown_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='modex',
            field=models.IntegerField(),
        ),
    ]
