# Generated by Django 4.2.2 on 2023-08-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_entry_modex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passdown',
            name='shift',
            field=models.CharField(choices=[('D', 'Days'), ('N', 'Nights'), ('M', 'Mids')], max_length=10),
        ),
    ]
