# Generated by Django 4.2.2 on 2023-08-31 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_passdown_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='passdown',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='passdown',
            name='shift',
            field=models.CharField(choices=[('Days', 'Days'), ('Nights', 'Nights'), ('Mids', 'Mids')], max_length=10),
        ),
    ]
