# Generated by Django 4.2.2 on 2023-08-31 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_remove_entry_passdown_passdown_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passdown',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='passdown',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leads.passdown'),
            preserve_default=False,
        ),
    ]
